version: '3.8'

services:
  front:
    container_name: logs_FRONT
    build: ./front
    ports:
      - 3001:3000
    networks:
      - backend
    volumes:
      - ./front:/front/

  back:
    container_name: logs_BACK
    build: ./back
    restart: on-failure:10
    environment:
      - DATABASE_URL=postgresql://pawelprzegon:4MnpxY8emdhJ@ep-plain-leaf-772245.eu-central-1.aws.neon.tech/logs?options=endpoint%3Dep-plain-leaf-772245
      - CORS_URL=http://localhost:3001
      - DB_TIMEOUT=30
    volumes:
      - ./back:/back/
      - /d/DATA:/back/volumes
    ports:
      - 8001:8000
    networks:
      - backend

networks:
  backend:
    driver: bridge
