version: '3.8'

services:
  front:
    container_name: logs_FRONT
    build: ./front
    ports:
      - 3001:3000
    networks:
      - app-network
    volumes:
      - ./front:/front/

  back:
    container_name: logs_BACK
    build: ./back
    restart: on-failure:10
    environment:
      - DATABASE_URL=postgresql+psycopg2://docker:docker@postgres:5432/logs
      - CORS_URL=http://localhost:3001
      - DB_TIMEOUT=30
    volumes:
      - ./back:/back/
      - /d/DATA:/back/volumes
    ports:
      - 8001:8000
    networks:
      - app-network

networks:
  app-network:
    external:
      name: database-net
