version: "3.8"

services:
  app:
    container_name: UNITS_app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4"
    volumes:
      - .:/app
      - /d/DATA/mutoh:/app/mutoh_api/volumes
      - /d/DATA/impala:/app/impala_api/volumes
      - /d/DATA/xeikon:/app/xeikon_api/volumes
      - /d/DATA/latex:/app/latex_api/volumes
    ports:
      - 8000:8000
